config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :blog_posts do
    resource :cover_image, only: [:destroy], module: :blog_posts
  end

  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_one_attached :cover_image
  has_rich_text :content
  validates :title, presence: true
  validates :content, presence: true

  scope :sorted, -> { order(arel_table[:published_at].desc.nulls_first).order(updated_at: :desc) }
  # scope :sorted, -> {order(published_at: :desc, updated_at: :desc )}
  scope :draft, -> {where(published_at: nil)}
  scope :published, -> {where("published_at <= ?", Time.current)}
  scope :scheduled, -> {where("published_at > ?", Time.current)}

  def should_generate_new_friendly_id?
    slug.nil? || title_changed?
  end

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #  :registerable,
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  def not_found_method
    render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
  end
end

app/controllers/blog_posts/cover_images_controller.rb
class BlogPosts::CoverImagesController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :authenticate_user!
  before_action :set_blog_post

  def destroy
    @blog_post.cover_image.purge_later

    respond_to do |format|
      format.html { redirect_to edit_blog_post_path(@blog_post) }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(@blog_post, :cover_image)) }
    end
  end

  private

  def set_blog_post
    @blog_post = BlogPost.find(params[:blog_post_id])
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog_post, except: [:index, :new, :create]

  def index
    @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
    @pagy, @blog_posts = pagy(@blog_posts)
  rescue Pagy::OverflowError, Pagy::VariableError
    redirect_to root_path(page: 1)
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :published_at, :cover_image)
  end

  def set_blog_post
    @blog_post = user_signed_in? ?
      BlogPost.friendly.find(params[:id]) : BlogPost.friendly.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/controllers/exceptions_controller.rb
class ExceptionsController < ApplicationController
  def show
    status_code = params[:code] || 500
    render status_code.to_s, status: status_code
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  include Heroicon::Engine.helpers

  def nav_link_class
    "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
  end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post do |form| %>
    <% if form.object.errors.any? %>
    <div>
        <% form.object.errors.full_messages.each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <% end %>

    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :cover_image %>
        <% if blog_post.cover_image.present? %>
        <div id="<%= dom_id(blog_post, :cover_image) %>">
            <%= image_tag blog_post.cover_image, class: "w-1/3" %>
            <%= link_to "Remove cover image", blog_post_cover_image_path(blog_post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        </div>
        <% end %>
        <%= form.file_field :cover_image %>
    </div>

    <div>
        <%= form.label :content %>
        <%= form.rich_text_area :content, class: "trix-editor" %>
    </div>

    <div>
        <%= form.label :published_at %>
        <%= form.datetime_select :published_at, include_blank: :true %>
    </div>

    <%= form.button %>
<% end %>

app/views/blog_posts/_pagination.html.erb
<% if @pagy.count > @pagy.items %>
    <div class="my-16">
        <%== pagy_nav(@pagy) %>
    </div>
<% end %>

app/views/blog_posts/edit.html.erb
<% content_for :title, "Valley Traveler :: Editing an existing article" %>

<h2>Edit blog post</h2>

<%= render partial: "form", locals: {blog_post: @blog_post} %>

<%= button_to "Delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"} %>

app/views/blog_posts/index.html.erb
<% content_for :title, "Valley Traveler :: List of current articles" %>

<%= render 'pagination' %>

<% @blog_posts.each do |blog_post| %>
    <div>
        <h2><%= link_to blog_post.title, blog_post %></h2>
        <% if blog_post.draft? %>
            <div class="p-2 rounded bg-gray-100 text-gray-900">draft</div>
        <% elsif blog_post.scheduled? %>
            <div class="p-2 rounded bg-blue-100 text-blue-900">
            scheduled (<%= blog_post.published_at.to_date.to_fs(:long) %>)
            </div>
        <% end %>
        <%= blog_post.content.to_plain_text.truncate(500) %>
    </div>
<% end %>

<%= render 'pagination' %>

app/views/blog_posts/new.html.erb
<% content_for :title, "Valley Traveler :: Add a blog post" %>

<h2>New</h2>

<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<% content_for :title, "Valley Traveler :: #{@blog_post.title}" %>

<%= link_to "Edit", edit_blog_post_path(@blog_post) if user_signed_in? %>

<%= image_tag @blog_post.cover_image if @blog_post.cover_image.present? %>

<h2><%= @blog_post.title %></h2>
<%= @blog_post.content %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if yield(:title).blank? %>
      <title>Valley Traveler :: Travel articles within and from the Silicon Valley</title>
    <% else %>
      <title><%= yield(:title) %></title>
    <% end %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Travel stories, explore the silicon valley, travel from the silicon valley. portugal, mexico, california">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render 'shared/header' %>
    <div class="prose mx-auto px-10 py-10">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="mx-auto mt-16 w-full max-w-container px-4 sm:px-6 lg:px-8">
  <div class="border-t border-slate-900/5 py-5">
    <p class="mt-4 text-center text-sm leading-6 text-slate-500">© <%= Time.now.year %> Ducklink Team. All rights reserved.</p>
    <div class="mt-4 flex items-center justify-center space-x-4 text-sm font-semibold leading-6">
      <%= link_to "About us", root_path %>
      <div class="h-4 w-px bg-slate-500/20"></div>
      <%= link_to "Home", root_path %>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class=<%= user_signed_in? ? "bg-red-800" : "bg-gray-800" %>>
    <div class="mx-auto px-6 md:px-12">
      <div class="flex h-16 items-center justify-between">
        <div class="flex items-center">
          <div>
            <%= image_tag("favicon-32x32.png", :alt => "favicon") %>
          </div>

          <div class="flex-shrink-0 ml-3">
            <a href="<%= root_path %>" class="text-white text-2xl">Valley Traveler</h2>
          </div>
          <div class="hidden sm:block">
            <div class="ml-8 flex items-baseline space-x-4">
              <a href="<%= root_path %>" class="<%= nav_link_class %>">Home</a>
              <% if user_signed_in? %>
                <%= link_to "New Post",
                  new_blog_post_path, class: nav_link_class %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>